"""Subscriber Channel Simulator.  Owner: E5

A mock of the channels a Libyan prepaid customer actually uses: a USSD menu
flow including a *61121#-style advance option, and an SMS preview, in Arabic
RTL with an English toggle.

Entering a test subscriber shows the exact offer, price and advance limit the
engine selected, with the message copy generated by the LLM and GROUNDED in the
engine's reason codes -- the LLM writes the wording, never the number.

Low engineering cost, disproportionate demo impact: it collapses the distance
between "we built a model" and "here is what the customer receives".

Run:  streamlit run apps/channel_sim/Home.py
"""

from __future__ import annotations

import streamlit as st

st.set_page_config(page_title="Channel Simulator", page_icon="mobile_phone", layout="centered")

st.title("Subscriber Channel Simulator")
lang = st.radio("Language", ["العربية", "English"], horizontal=True)

tab_ussd, tab_sms = st.tabs(["USSD  *61121#", "SMS"])

with tab_ussd:
    st.warning("Not implemented yet -- E5, sprint day 12.", icon=":material/construction:")

with tab_sms:
    st.warning("Not implemented yet -- E5, sprint day 12.", icon=":material/construction:")

# TODO(E5): render Arabic through arabic-reshaper + python-bidi (the `rtl`
# extra) directly -- there is no shared preprocessing module in this branch,
# because Arabic text handling left with M6.
#
# The LLM writes the copy from the reason codes the decision engine already
# returned; it must not invent a price, a bonus or a limit, and it sits here in
# the demo surface rather than anywhere near the decision path. If the engine
# returned no offer, the simulator shows no offer.
