"""Ask an assistant its evaluation questions for real, and write what it did to a report.

`uv run python -m assistants.evaluate chatbot` sends every question in
`eval/chatbot_questions.toml` through the live prepaid service and Groq, checks each answer,
and writes `reports/chatbot_eval.md`.
This is the only code that spends Groq tokens; the unit tests never call Groq.
"""

import argparse
import os
import re
import sys
import time
import tomllib
import unicodedata
from datetime import UTC, datetime
from pathlib import Path

from assistants import chatbot_tools, llm, service_client

ROOT = Path(__file__).parents[2]

# Words the customer chatbot must never use, whatever it was asked: it has no risk data, and
# a customer is not told how likely the operator thinks they are to leave (decision 10).
CHATBOT_NEVER_SAY = ["high risk", "medium risk", "low risk", "risk band", "probability"]


def _mostly_arabic(text: str) -> bool:
    return len(re.findall(r"[\u0600-\u06ff]", text)) > len(re.findall(r"[A-Za-z]", text))


def check(question: dict, turn: llm.Turn) -> list[str]:
    """Every expectation of `question` that `turn` failed, in plain words."""
    failures = []
    # The model writes narrow no-break spaces ("5\u202fLYD"); compare what a reader sees.
    reply = unicodedata.normalize("NFKC", turn.reply).replace("\u2019", "'").casefold()
    called = [call.name for call in turn.calls]
    for tool in question.get("tools", []):
        if tool not in called:
            failures.append(f"did not call {tool}")
    for tool, expected in question.get("arguments", {}).items():
        made = [call.arguments for call in turn.calls if call.name == tool]
        if not any(expected.items() <= arguments.items() for arguments in made):
            failures.append(f"did not call {tool} with {expected}")
    say_any = question.get("say_any", [])
    if say_any and not any(text.casefold() in reply for text in say_any):
        failures.append("said none of: " + ", ".join(say_any))
    for text in question.get("never_say", []) + CHATBOT_NEVER_SAY:
        if text.casefold() in reply:
            failures.append(f"said {text!r}")
    if _mostly_arabic(turn.reply) != chatbot_tools.is_arabic(question["text"]):
        failures.append("answered in the other language")
    if "%" in turn.reply and "%" not in question["text"]:
        failures.append("gave a percentage nobody asked about")
    if turn.replaced_because:
        failures.append(f"the model's reply was replaced: {turn.replaced_because}")
    return failures


def _quote(text: str) -> str:
    return "\n".join(f"> {line}" if line else ">" for line in text.splitlines())


def report(name: str, base_url: str, health: dict, results: list[tuple]) -> str:
    passed = sum(1 for _, _, failures in results if not failures)
    replaced = sum(1 for _, turn, _ in results if turn.replaced_because)
    campaign = (health.get("latest_outputs") or {}).get("campaign_id") or "none"
    lines = [
        f"# {name.capitalize()} evaluation",
        "",
        f"Generated by `uv run python -m assistants.evaluate {name}` on "
        f"{datetime.now(UTC):%Y-%m-%d %H:%M} UTC.",
        f"Model `{llm.MODEL}` on Groq; prepaid service at `{base_url}`, status "
        f"`{health.get('status')}`, campaign `{campaign[:12]}`.",
        "",
        f"**{passed} of {len(results)} questions passed every check.**",
        f"{replaced} replies were replaced by the safe answer.",
        "",
        "| Question | Tools called | Result |",
        "|---|---|---|",
    ]
    for question, turn, failures in results:
        tools = ", ".join(call.name for call in turn.calls) or "none"
        verdict = "pass" if not failures else "fail: " + "; ".join(failures)
        lines.append(f"| `{question['id']}` | {tools} | {verdict} |")
    lines.append("")
    for question, turn, failures in results:
        lines += [f"## `{question['id']}`", ""]
        if question.get("subscriber"):
            lines += [f"Signed in as `{question['subscriber']}`.", ""]
        lines += [
            "Asked:",
            "",
            _quote(question["text"]),
            "",
            "Answered:",
            "",
            _quote(turn.reply),
            "",
        ]
        for call in turn.calls:
            lines.append(f"- called `{call.name}` with `{call.arguments}`")
        if failures:
            lines += [""] + [f"- **failed:** {failure}" for failure in failures]
        lines.append("")
    return "\n".join(lines)


def run_chatbot(base_url: str, pause: float) -> str:
    key = os.environ["PREPAID_CHURN_CHATBOT_KEY"]
    health = service_client.health(base_url)
    questions = tomllib.loads((ROOT / "eval" / "chatbot_questions.toml").read_text("utf-8"))
    complete = llm.groq_complete()
    results = []
    for number, question in enumerate(questions["question"]):
        if number:
            time.sleep(pause)
        arabic = chatbot_tools.is_arabic(question["text"])
        tools = chatbot_tools.build_tools(base_url, key, question.get("subscriber"), arabic)
        turn = llm.run_turn(
            chatbot_tools.system_prompt(arabic),
            [],
            question["text"],
            tools,
            complete,
            chatbot_tools.fallback,
        )
        if (turn.replaced_because or "").startswith("the language model is unavailable"):
            # Every later question would fail the same way; say why and stop.
            raise SystemExit(f"Stopped at {question['id']}: {turn.replaced_because}")
        failures = check(question, turn)
        results.append((question, turn, failures))
        print(f"{question['id']}: {'pass' if not failures else 'FAIL ' + '; '.join(failures)}")
    return report("chatbot", base_url, health, results)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("assistant", choices=["chatbot"])
    parser.add_argument(
        "--url", default=os.environ.get("PREPAID_CHURN_URL", "http://127.0.0.1:8000")
    )
    parser.add_argument(
        "--pause",
        type=float,
        default=25.0,
        help="Seconds between questions, to stay inside Groq's free 8K tokens a minute.",
    )
    args = parser.parse_args(argv)
    text = run_chatbot(args.url, args.pause)
    path = ROOT / "reports" / f"{args.assistant}_eval.md"
    path.write_text(text, encoding="utf-8")
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
