"""Aggregate retention planning report, including all assumptions (T11)."""

from dataclasses import asdict
from decimal import ROUND_CEILING, Decimal

import pandas as pd

from prepaid_churn.profile import markdown_table
from prepaid_churn.retention import RetentionPolicy


def decisions_report(
    decisions: pd.DataFrame, comparison: pd.DataFrame, offers: pd.DataFrame, policy: RetentionPolicy
) -> str:
    proposed = decisions["status"].eq("proposed")
    unavailable = decisions["value_status"].eq("risk_unavailable").sum()
    assumptions = pd.DataFrame({"value": pd.Series(asdict(policy)).astype(str)})
    costs = offers[["offer_id", "price_lyd"]].copy()
    costs["estimated_delivery_cost_lyd"] = [
        float(
            (
                Decimal(str(row.price_lyd))
                * Decimal(
                    str(
                        policy.share_of_price_unlimited
                        if row.data_unlimited or row.voice_unlimited
                        else policy.share_of_price_metered
                    )
                )
                * 1000
            ).to_integral_value(rounding=ROUND_CEILING)
        )
        / 1000
        for row in offers.itertuples(index=False)
    ]
    costs["assumed_share_saved"] = [
        policy.offpeak_share_saved if offer == policy.preferred_offer_id else policy.share_saved
        for offer in offers["offer_id"]
    ]
    reasons = decisions["decision_code"].value_counts().rename("customers").to_frame()
    preferred = int(
        decisions.loc[proposed, "recommended_offer_id"].eq(policy.preferred_offer_id).sum()
    )
    offer_mix = (
        [
            f"{preferred:,} of {int(proposed.sum()):,} proposals are "
            f"`{policy.preferred_offer_id}`, the offer assumed to save "
            f"{policy.offpeak_share_saved:.0%} of churners instead of {policy.share_saved:.0%}; "
            "the offer mix follows from that assumption, not from measured response.",
        ]
        if proposed.any()
        else []
    )
    lines = [
        "# T11 retention decisions",
        "",
        "Generated by `uv run churn decide`; all monetary outcomes below are planning scenarios.",
        f"Policy version: `{policy.version}`.",
        f"Customers: {len(decisions):,}; proposals: {int(proposed.sum()):,}; "
        f"no offer: {int((~proposed).sum()):,}; "
        f"random holdout: {int(decisions['holdout'].sum()):,}.",
        f"Expected delivery cost: {decisions['expected_cost_lyd'].sum():.3f} LYD "
        f"against a {policy.budget_lyd:.3f} LYD budget.",
        f"Assumed net retained revenue less delivery cost: "
        f"{decisions['expected_net_value_lyd'].sum():.3f} LYD, not measured profit.",
        f"Risk unavailable for {unavailable:,} active customers; these customers get no offer.",
        "No real churn bundle was used in this run; zero proposals are a fail-closed readiness "
        "result, not evidence about campaign effectiveness."
        if unavailable
        else "Risk and value come from the gated churn and frozen tier artifacts.",
        "",
        "## Assumptions beside the results",
        "",
        "All T11 assumptions are in `data/operator/retention.toml`.",
        "Delivery shares start from T16's estimates, 25% for metered and 35% for unlimited "
        "products; they are not audited operator costs.",
        "The preferred morning bonus assumes a different share saved; no campaign data "
        "establishes this advantage, and changing it can change the winning offer.",
        *offer_mix,
        "",
        markdown_table(assumptions, "Setting"),
        "",
        "Expected net value = churn probability x assumed share of churners saved x "
        "T10 base 12-month revenue scenario - estimated delivery cost.",
        "T10 retains the assumed LYD conversion, constant monthly hazard and spend, "
        "no reactivation, growth, discounting or margin adjustment.",
        "These are neither validated CLV nor causal uplift or measured savings.",
        "The customer receives the catalogue product as a bonus; catalogue prices are unchanged.",
        "Delivery costs round up to dirhams; budgets round down, so rounding cannot overspend.",
        "",
        "## Guardrails and no-offer outcomes",
        "",
        "Already-silent, unscored, low-risk and held-out customers get no proposal.",
        "The cap is per customer in this campaign, not a cumulative annual retention budget.",
        "Current bundles are T18's behavioural mapping, not observed operator subscriptions.",
        "A customer mapped to a monthly bundle above the configured base cannot receive "
        "a cheaper unlimited product, regardless of churn risk.",
        "5G and shared-family products are excluded because device, coverage and membership "
        "eligibility are absent; catalogue presence alone does not establish eligibility.",
        "A bonus must include at least one service the customer uses; data-only offers require "
        "data use, and voice-only offers require voice use.",
        "The morning product's 06:00-11:00 restriction is stated in both reasons; "
        "the export cannot establish time-of-day preference or incremental usage.",
        "Each customer first gets the highest-net-value feasible candidate; ties prefer the "
        "configured bonus then sorted offer ID.",
        "Only positive candidates are considered; greedy allocation sorts net value descending "
        "and subscriber ID on ties, skipping candidates the remaining budget cannot fund.",
        "This is a greedy allocation, not a proof of the optimal knapsack solution.",
        "",
        markdown_table(reasons, "Decision"),
        "",
        "## Comparison at the same expected spend",
        "",
        markdown_table(comparison.set_index("strategy").round(4), "Strategy"),
        "",
        "Every row spends exactly the targeted allocation in expectation, "
        "not the configured ceiling.",
        "The untargeted baseline gives every feasible active, scored, non-holdout customer "
        "the same inclusion probability: targeted spend divided by their total offer cost.",
        "It includes low-risk and nonpositive-value candidates to represent treating everyone.",
        "The risk-only baseline ranks this same pool by churn probability and uses a "
        "fractional last inclusion probability to match spend exactly.",
        "Both baselines retain relevance, eligibility and per-customer/cannibalisation guards, "
        "and use each person's same best candidate; they isolate allocation policy.",
        "Fractional expected counts are diagnostic lotteries, never executable campaign rows.",
        "Zero spend makes all three scenarios zero and supports no targeting-effect claim.",
        "The comparison evaluates the stated assumptions, not an experimentally measured benefit.",
        "The targeted plan is chosen to maximise this same assumed net value, so it scores "
        "highest by construction; the table checks the allocation against its own "
        "assumptions, not whether targeting works.",
        "Risk only is scored with the same T10 scenario, whose constant-risk assumption makes "
        "the riskiest customers look least worth saving (decision 41).",
        "",
        "## Review and holdout",
        "",
        "A seeded SHA-256 lottery assigns approximately the configured holdout fraction "
        "independently of input order and batch size; those customers never get an offer.",
        "The lottery depends only on the subscriber ID and the policy seed, so every campaign "
        "with this seed holds out the same customers: a permanent control group, kept on "
        "purpose so a measured campaign can compare them with customers who got offers "
        "(decision 43).",
        "Keep the campaign snapshot and holdout assignment for a future measured campaign.",
        "No response outcomes or treatment effects are generated here.",
        "`churn decide` writes proposals and an empty released campaign.",
        "`churn approve --proposals <proposals.json> --reviewer <name>` resolves all pending "
        "proposals; repeat `--subscriber-id` to select individual pending proposals.",
        "Use `--reject` to reject and `--note` for a review note.",
        "Use `--refresh` with a reviewer name to rebuild derived files after an interruption "
        "without deciding any remaining proposals.",
        "Only approved rows enter `released.csv`; it omits internal risk and value fields.",
        "Reviews record subscriber, reviewer, UTC time, decision, note and campaign fingerprint.",
        "Files provide local integrity and review bookkeeping, not authenticated identity; "
        "T15 must add access control before a shared service can approve or expose offers.",
        "No offers are sent or provisioned by these commands.",
        "",
        "## Per-offer delivery estimates and effect assumptions",
        "",
        "Rows include the entire catalogue; "
        "eligibility rules can exclude an offer from a campaign.",
        "",
        markdown_table(costs.set_index("offer_id"), "Offer"),
        "",
    ]
    return "\n".join(lines)
