"""Training-only comparison of business tiers and exploratory clusters (ticket T10)."""

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from matplotlib.figure import Figure
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import adjusted_rand_score, silhouette_score
from sklearn.preprocessing import StandardScaler

from prepaid_churn.profile import markdown_table
from prepaid_churn.value import (
    SCORE_COLUMNS,
    TIERS,
    TierModel,
    apply_tiers,
    expected_months,
)
from prepaid_churn.windows import SEED

SILHOUETTE_SAMPLE = 2000
PLOT_SAMPLE = 2000
HIERARCHICAL_SAMPLE = 300


@dataclass
class ClusterComparison:
    scores: pd.DataFrame
    labels: np.ndarray | None
    scaled: np.ndarray
    sample: np.ndarray
    chosen_k: int | None


def compare_clusters(tiers: pd.DataFrame) -> ClusterComparison:
    """Select k=2..8 by silhouette on one fixed sample; ties prefer smaller k."""
    scaled = StandardScaler().fit_transform(tiers[SCORE_COLUMNS])
    sample = np.sort(
        np.random.default_rng(SEED).choice(
            len(tiers), min(SILHOUETTE_SAMPLE, len(tiers)), replace=False
        )
    )
    distinct = len(np.unique(scaled, axis=0))
    rows, best_labels, best_k, best_score = [], None, None, -np.inf
    for k in range(2, min(8, distinct, len(tiers) - 1) + 1):
        model = KMeans(n_clusters=k, n_init=10, random_state=SEED).fit(scaled)
        labels = model.labels_[sample]
        # A small or heavily tied sample may not contain two represented clusters.
        silhouette = (
            float(silhouette_score(scaled[sample], labels))
            if 1 < len(np.unique(labels)) < len(sample)
            else np.nan
        )
        rows.append({"k": k, "silhouette": silhouette, "inertia": float(model.inertia_)})
        if np.isfinite(silhouette) and silhouette > best_score:
            best_score, best_k, best_labels = silhouette, k, model.labels_.copy()
    scores = pd.DataFrame(rows, columns=["k", "silhouette", "inertia"])
    return ClusterComparison(scores, best_labels, scaled, sample, best_k)


def write_cluster_plots(comparison: ClusterComparison, directory: Path) -> None:
    """Write aggregate plots without subscriber IDs, with bounded plot/linkage samples."""
    if comparison.chosen_k is None:
        return
    directory.mkdir(parents=True, exist_ok=True)
    projected = PCA(n_components=2).fit(comparison.scaled)
    sample = comparison.sample[:PLOT_SAMPLE]
    points = projected.transform(comparison.scaled[sample])
    figure = Figure(figsize=(8, 5), layout="constrained")
    axis = figure.subplots()
    for label in range(comparison.chosen_k):
        selected = comparison.labels[sample] == label
        axis.scatter(
            points[selected, 0], points[selected, 1], s=9, alpha=0.45, label=f"Cluster {label + 1}"
        )
    variance = projected.explained_variance_ratio_
    axis.set(
        xlabel=f"PC1 ({variance[0]:.1%} of variance)",
        ylabel=f"PC2 ({variance[1]:.1%} of variance)",
        title=f"Training value scores: PCA, {len(sample):,} sampled customers",
    )
    axis.legend(markerscale=2, fontsize="small")
    figure.savefig(directory / "tiers_pca.png", dpi=150)

    sample = np.random.default_rng(SEED).choice(
        len(comparison.scaled), min(HIERARCHICAL_SAMPLE, len(comparison.scaled)), replace=False
    )
    tree = linkage(comparison.scaled[sample], method="ward")
    figure = Figure(figsize=(9, 5), layout="constrained")
    axis = figure.subplots()
    dendrogram(tree, truncate_mode="lastp", p=20, show_leaf_counts=True, ax=axis)
    axis.set(
        title=f"Ward linkage: {len(sample):,} training customers, last 20 groups",
        xlabel="Group index or (number of customers); no subscriber IDs",
        ylabel="Ward merge distance",
    )
    figure.savefig(directory / "tiers_dendrogram.png", dpi=150)


def tiers_report(train: pd.DataFrame, model: TierModel, comparison: ClusterComparison) -> str:
    tiers = apply_tiers(train, model)
    counts = tiers["value_tier"].value_counts().reindex(TIERS, fill_value=0)
    distribution = pd.DataFrame({"customers": counts, "share": (counts / len(tiers)).round(4)})
    cutoffs = pd.DataFrame(
        {
            name: values if values is not None else ["neutral"] * 4
            for name, values in model.cutoffs.items()
        },
        index=["20%", "40%", "60%", "80%"],
    ).T
    cutoffs = cutoffs.map(lambda value: round(value, 4) if isinstance(value, float) else value)
    lines = [
        "# T10 value tiers",
        "",
        "Generated by `uv run churn fit-tiers` from the active training customers in window A.",
        "Validation and test frames, labels and churn model artifacts are not read.",
        f"Training customers: {len(train):,}; frozen tier artifact: `{model.version}`.",
        "The source behaviour is upGrad prepaid data, not Almadar subscriber behaviour.",
        "",
        "## Measures and rules",
        "",
        "- Recency: minimum days since airtime or data recharge over the two feature months.",
        "  Without a recharge it is a lower bound censored at the window length.",
        "- Frequency: average monthly airtime plus data recharge counts, a count proxy.",
        "  Separate source counters can overlap; these are not deduplicated transactions.",
        "- Monetary: average monthly airtime plus data recharge amount, using T18's LYD rate.",
        f"  The frozen rate is {model.rate:.10f} LYD per source recharge unit.",
        "  It inherits the assumed ARPU anchor in `data/almadar/market.toml` (decision 42); "
        "this is not observed operator revenue.",
        "- Tenure: the existing age-on-network snapshot in days, with T4's timing limitation.",
        "- Engagement: how many of voice, data, packs and roaming were used in either month.",
        "",
        "Each dimension receives a score from 1 to 5 using training quintile cutoffs.",
        "Recency is negated before ranking so a more recent recharge scores higher.",
        "The equally weighted mean of those scores is cut into five named value tiers.",
        "A value equal to a cutoff belongs to the lower interval; tied customers stay together.",
        "Constant training dimensions receive neutral score 3 even at serving time.",
        "Missing activity blocks follow the input contract; unexpected missing inputs fail.",
        "Tier proportions need not be 20%, and not every tier must be populated.",
        "Cutoffs and the monetary rate travel together in the versioned JSON artifact.",
        "No statistics are fitted on the export being scored.",
        "",
        markdown_table(distribution, "Tier"),
        "",
        markdown_table(cutoffs, "Measure (recency negated)"),
        "",
        "## Rules compared with clusters",
        "",
        "K-Means uses standardized dimension scores fitted on the same training customers.",
        "We search k=2..8 (bounded by distinct score rows), with seed 42 and 10 initializations.",
        f"Silhouette uses one fixed sample of {len(comparison.sample):,} customers, capped at "
        f"{SILHOUETTE_SAMPLE:,}, to bound quadratic distance work.",
    ]
    if comparison.chosen_k is None:
        lines += [
            "Too few distinct represented groups for a valid silhouette comparison.",
            "No clusters or plots are claimed for this degenerate training set.",
        ]
    else:
        best = comparison.scores.set_index("k").loc[comparison.chosen_k, "silhouette"]
        agreement = adjusted_rand_score(tiers["value_tier"], comparison.labels)
        cross = pd.crosstab(tiers["value_tier"], comparison.labels + 1).reindex(TIERS, fill_value=0)
        lines += [
            markdown_table(comparison.scores.set_index("k").round(4), "k"),
            "",
            f"Selected k={comparison.chosen_k}, silhouette={best:.4f}.",
            "The separation is weak under a descriptive 0.5 heuristic."
            if best < 0.5
            else "There is visible separation in these discretized training scores.",
            "The five tiers remain a business reporting convention, not discovered natural "
            "segments or evidence of response to retention offers.",
            "Discretization itself can create apparent separation; "
            "silhouette is not a release gate.",
            f"Adjusted Rand agreement between tier and cluster labels: {agreement:.4f}.",
            "Cluster numbers are arbitrary; the table counts customers by tier and cluster.",
            "",
            markdown_table(cross, "Tier / cluster"),
            "",
            "![PCA of training clusters](tiers_pca.png)",
            "",
            "![Sampled Ward dendrogram](tiers_dendrogram.png)",
            "",
            "PCA is for visualization only; tier assignment does not use its components.",
            f"Ward linkage uses at most {HIERARCHICAL_SAMPLE} randomly sampled training rows.",
        ]
    scenarios = pd.DataFrame({"monthly hazard": [0.0, 0.05, 0.1, 0.2, 0.5, 1.0]})
    scenarios["expected months"] = expected_months(scenarios["monthly hazard"].to_numpy())
    scenarios["value per 10 LYD/month"] = 10 * scenarios["expected months"]
    lines += [
        "",
        "## 12-month value scenario, not validated CLV",
        "",
        "For monthly churn probability p, expected months = sum((1-p)^m, m=1..12).",
        "This assumes a constant hazard, constant monthly spend, no reactivation, no growth, "
        "no discounting and no margin adjustment.",
        "The constant hazard and the absence of reactivation were checked on 2026-09-26 "
        "against the validation customers' next month, and neither holds (decision 41): "
        "risk moves back toward the average after a month, and 28.1% of customers silent in "
        "one month were active the next.",
        "These amounts therefore understate high-risk customers and overstate low-risk ones; "
        "ticket T23 replaces this scenario.",
        "The horizon starts at the next month end; p=0 gives 12 months and p=1 gives zero.",
        "We multiply expected months by the two-month average spend in LYD.",
        "The low/base/high scenarios multiply p by 1.5/1/0.5, clipped to [0,1].",
        "These are assumption sensitivities, not confidence bounds, causal savings or profit.",
        "Already-silent customers have no probability and no value estimate.",
        "Without a gated churn bundle, `churn tiers --tiers-only` leaves estimates empty "
        "and marks active customers `risk_unavailable`.",
        "The table below uses illustrative hazards, "
        "not additional churn predictions or test results.",
        "",
        markdown_table(scenarios.set_index("monthly hazard").round(4), "Illustrative p"),
        "",
        "The frozen churn model and the spent test window were not changed or reevaluated.",
        "",
    ]
    return "\n".join(lines)
