"""Model training (ticket T6): a logistic regression baseline and LightGBM.

Neither model uses class weights, so raw probabilities stay close to the real
churn rate before calibration (T7). LightGBM's early stopping uses a slice of
the training customers, so the validation customers stay untouched for
calibration, threshold choice and model comparison.
"""

import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, brier_score_loss, log_loss, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler

from prepaid_churn.schema import ID
from prepaid_churn.windows import LABEL, SEED

EARLY_STOPPING_SHARE = 0.10
EARLY_STOPPING_ROUNDS = 100


def feature_columns(frame: pd.DataFrame) -> list[str]:
    return [column for column in frame.columns if column not in (ID, LABEL)]


def signed_log1p(values):
    """Compress heavy-tailed amounts for the linear model while keeping the sign."""
    return np.sign(values) * np.log1p(np.abs(values))


def logistic_regression():
    return make_pipeline(
        FunctionTransformer(signed_log1p),
        StandardScaler(),
        LogisticRegression(max_iter=5000),
    )


def lightgbm(seed: int = SEED, n_estimators: int = 3000) -> lgb.LGBMClassifier:
    return lgb.LGBMClassifier(
        n_estimators=n_estimators,
        learning_rate=0.03,
        num_leaves=31,
        min_child_samples=50,
        subsample=0.8,
        subsample_freq=1,
        colsample_bytree=0.8,
        reg_lambda=1.0,
        random_state=seed,
        deterministic=True,
        force_row_wise=True,
        n_jobs=1,
        verbose=-1,
    )


def train_models(train: pd.DataFrame, seed: int = SEED) -> dict:
    """Fit both models on the train customers; LightGBM picks its tree count by early stopping."""
    features = feature_columns(train)
    x, y = train[features], train[LABEL]

    baseline = logistic_regression().fit(x, y)

    fit_index, stop_index = train_test_split(
        train.index, test_size=EARLY_STOPPING_SHARE, stratify=y, random_state=seed
    )
    probe = lightgbm(seed).fit(
        x.loc[fit_index],
        y.loc[fit_index],
        eval_X=(x.loc[stop_index],),
        eval_y=(y.loc[stop_index],),
        eval_metric="binary_logloss",
        callbacks=[lgb.early_stopping(EARLY_STOPPING_ROUNDS, verbose=False)],
    )
    trees = max(probe.best_iteration_ or 0, 1)
    booster = lightgbm(seed, n_estimators=trees).fit(x, y)

    return {"logistic_regression": baseline, "lightgbm": booster}


def predict(model, frame: pd.DataFrame) -> np.ndarray:
    return model.predict_proba(frame[feature_columns(frame)])[:, 1]


def metrics(y_true, probability) -> dict[str, float]:
    return {
        "roc_auc": roc_auc_score(y_true, probability),
        "pr_auc": average_precision_score(y_true, probability),
        "log_loss": log_loss(y_true, probability),
        "brier": brier_score_loss(y_true, probability),
        "mean_probability": float(np.mean(probability)),
        "churn_rate": float(np.mean(y_true)),
    }


def evaluation_table(models: dict, frame: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame(
        {name: metrics(frame[LABEL], predict(model, frame)) for name, model in models.items()}
    ).T


def top_importances(booster: lgb.LGBMClassifier, count: int = 15) -> pd.Series:
    gains = booster.booster_.feature_importance(importance_type="gain")
    importances = pd.Series(gains, index=booster.feature_name_)
    return (importances / importances.sum()).sort_values(ascending=False).head(count)


def training_report(models: dict, train: pd.DataFrame, validation: pd.DataFrame) -> str:
    from prepaid_churn.profile import markdown_table

    booster = models["lightgbm"]
    return "\n".join(
        [
            "# T6 training",
            "",
            "Generated by `uv run churn train`.",
            "Probabilities are not calibrated yet (T7), so ranking metrics matter most here.",
            "",
            f"Train rows: {len(train)}. Validation rows: {len(validation)}. "
            f"Features: {len(feature_columns(train))}. LightGBM trees: {booster.n_estimators}.",
            "",
            "## Validation metrics (window A, validation customers)",
            "",
            markdown_table(evaluation_table(models, validation), "model"),
            "",
            "## LightGBM: top features by share of total gain",
            "",
            markdown_table(top_importances(booster).to_frame("gain_share"), "feature"),
            "",
        ]
    )
