"""Windows, labels, eligibility and the customer split (ticket T4).

Features always come from a "previous" and a "current" month, and the label
from the month after. Window A (months 6, 7, label month 8) trains and
validates; window B (months 7, 8, Kaggle's month 9 label) tests. Only
customers still active in the current month are eligible (decision 12).
"""

from dataclasses import dataclass

import pandas as pd
from sklearn.model_selection import train_test_split

from prepaid_churn.data import LABEL_COLUMN, column_name, monthly_columns
from prepaid_churn.labels import usage_inactive
from prepaid_churn.schema import ID, TENURE

LABEL = "churn"
TENURE_FEATURE = "tenure_days"
SEED = 42
HIGH_VALUE_QUANTILE = 0.70
SPLITS = ("train", "validation", "test")


@dataclass(frozen=True)
class Window:
    name: str
    previous: int
    current: int
    label_month: int
    kaggle_label: bool  # True: the label comes from Kaggle's column, not from our rule


WINDOW_A = Window("A", previous=6, current=7, label_month=8, kaggle_label=False)
WINDOW_B = Window("B", previous=7, current=8, label_month=9, kaggle_label=True)
WINDOW_OF_SPLIT = {"train": WINDOW_A, "validation": WINDOW_A, "test": WINDOW_B}


def window_features(df: pd.DataFrame, window: Window) -> pd.DataFrame:
    """`prev_<base>` and `cur_<base>` for every base present in both months, plus tenure.

    Nothing from a month after `window.current` is used. Tenure (`aon`) is a
    snapshot taken when the data was extracted; the one-month difference
    between windows is small against its 180 to 4,337 day range.
    """
    table = monthly_columns(df.columns)[[window.previous, window.current]].dropna()
    features = {TENURE_FEATURE: df[TENURE]}
    for prefix, month in (("prev", window.previous), ("cur", window.current)):
        for base, name in table[month].items():
            features[f"{prefix}_{base}"] = df[name]
    return pd.DataFrame(features, index=df.index)


def window_label(df: pd.DataFrame, window: Window) -> pd.Series:
    """1 if the customer is inactive in the label month (upGrad's usage-based churn)."""
    if window.kaggle_label:
        return df[LABEL_COLUMN].astype(int)
    return usage_inactive(df, window.label_month).astype(int)


def active_in_current_month(df: pd.DataFrame, window: Window) -> pd.Series:
    """Eligibility: customers already silent in the current month are not scored (decision 12)."""
    return ~usage_inactive(df, window.current)


def recharge_amount(df: pd.DataFrame, month: int) -> pd.Series:
    """Airtime plus data recharge amount in a month (upGrad's definition of customer value)."""
    data = df[column_name("total_rech_data", month)] * df[column_name("av_rech_amt_data", month)]
    return df[column_name("total_rech_amt", month)] + data


def high_value(
    df: pd.DataFrame, window: Window, quantile: float = HIGH_VALUE_QUANTILE
) -> pd.Series:
    """Customers whose average recharge amount over the window is in the top 30%."""
    amount = (recharge_amount(df, window.previous) + recharge_amount(df, window.current)) / 2
    return amount >= amount.quantile(quantile)


def split_customers(df: pd.DataFrame, seed: int = SEED) -> pd.Series:
    """Split customers 70/15/15, stratified by the window A label; one split name per row."""
    label = window_label(df, WINDOW_A)
    train, rest = train_test_split(df.index, test_size=0.30, stratify=label, random_state=seed)
    validation, test = train_test_split(
        rest, test_size=0.50, stratify=label.loc[rest], random_state=seed
    )
    split = pd.Series("train", index=df.index)
    split.loc[validation] = "validation"
    split.loc[test] = "test"
    return split


def build_datasets(
    cleaned: pd.DataFrame, high_value_only: bool = False, seed: int = SEED
) -> dict[str, pd.DataFrame]:
    """Train, validation and test frames: `id`, window features and the `churn` label."""
    split = split_customers(cleaned, seed)
    datasets = {}
    for name in SPLITS:
        window = WINDOW_OF_SPLIT[name]
        eligible = active_in_current_month(cleaned, window)
        if high_value_only:
            eligible &= high_value(cleaned[eligible], window).reindex(
                cleaned.index, fill_value=False
            )
        rows = cleaned[split.eq(name) & eligible]
        frame = window_features(rows, window)
        frame.insert(0, ID, rows[ID])
        frame[LABEL] = window_label(rows, window)
        datasets[name] = frame.reset_index(drop=True)
    return datasets


def dataset_report(
    cleaned: pd.DataFrame, datasets: dict[str, pd.DataFrame], seed: int = SEED
) -> str:
    split = split_customers(cleaned, seed)
    lines = [
        "# T4 datasets",
        "",
        "Generated by `uv run churn build-dataset`.",
        "",
        "| Split | Window | Customers in split | Already silent (excluded) | Rows | Churn rate |",
        "|---|---|---|---|---|---|",
    ]
    for name in SPLITS:
        window = WINDOW_OF_SPLIT[name]
        in_split = split.eq(name)
        silent = int((in_split & ~active_in_current_month(cleaned, window)).sum())
        frame = datasets[name]
        months = f"{window.previous}, {window.current} -> {window.label_month}"
        lines.append(
            f"| {name} | {window.name} ({months}) | {int(in_split.sum())} | {silent} "
            f"| {len(frame)} | {frame[LABEL].mean():.4f} |"
        )
    features = [column for column in datasets["train"].columns if column not in (ID, LABEL)]
    lines += ["", f"Feature columns: {len(features)} (identical in every split).", ""]
    return "\n".join(lines)
